version: '3.8'

services:
  django:
    tty: true
    build: .
    container_name: django
    command:
      sh -c "export DJANGO_SETTINGS_MODULE=settings.prod &&
      python manage.py makemigrations --fix -b [main/master] &&
      python manage.py migrate && 
      python manage.py loaddata fixtures/UserRoles.json &&
      python manage.py collectstatic --noinput &&
      gunicorn presales.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
      - static:/usr/src/app/static
    expose:
      - "8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static:/usr/src/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  pgdata:
  static: